export type ApplicationErrorCode =
  | "INVALID_ENVIRONMENT"
  | "INVALID_ENVIRONMENT_VARIABLE"
  | "INVALID_LOG_LEVEL"
  | "EMBEDDING_PROVIDER_ERROR"
  | "GENERATION_PROVIDER_ERROR"
  | "GENERATED_DOCUMENT_REPOSITORY_ERROR"
  | "GENERATED_RESUME_REPOSITORY_ERROR"
  | "APPLICATION_REPOSITORY_ERROR"
  | "APPLICATION_EVENT_REPOSITORY_ERROR"
  | "PDF_COMPILER_ERROR"
  | "RESUME_RENDERING_ERROR"
  | "MISSING_ENVIRONMENT_VARIABLE"
  | "SUPABASE_CONFIGURATION_ERROR"
  | "INVALID_DISCOVERY_REQUEST"
  | "INVALID_JOB_DATA"
  | "JOB_REPOSITORY_ERROR"
  | "JOB_MATCH_SCORE_REPOSITORY_ERROR"
  | "PARSED_JOB_PROFILE_REPOSITORY_ERROR"
  | "JOB_NOT_FOUND"
  | "PARSED_JOB_PROFILE_NOT_FOUND"
  | "USER_PROFILE_NOT_FOUND"
  | "USER_PROFILE_REPOSITORY_ERROR"
  | "RESUME_FRAGMENT_REPOSITORY_ERROR"
  | "INVALID_RESUME_FRAGMENT"
  | "RESUME_CONTEXT_NOT_FOUND"
  | "INVALID_PARSE_REQUEST"
  | "INVALID_GENERATION_REQUEST"
  | "INVALID_GENERATED_DOCUMENT"
  | "INVALID_RENDER_REQUEST"
  | "INVALID_LIFECYCLE_REQUEST"
  | "INVALID_LIFECYCLE_STATE"
  | "INVALID_APPLICATION_TRANSITION"
  | "APPLICATION_NOT_FOUND"
  | "MANUAL_OVERRIDE_REASON_REQUIRED"
  | "INVALID_ATS_AUTOMATION_REQUEST"
  | "INVALID_RESUME_PDF_PATH"
  | "ATS_STRATEGY_NOT_FOUND"
  | "ATS_STRATEGY_EXECUTION_UNAVAILABLE"
  | "INVALID_WORKDAY_TRANSITION"
  | "WORKDAY_STATE_NOT_DETECTED"
  | "INVALID_ATS_ARTIFACT_PATH"
  | "ATS_RETRY_EXHAUSTED"
  | "RESUME_UPLOAD_VERIFICATION_FAILED"
  | "SEMANTIC_LOCATOR_NOT_FOUND"
  | "UNSAFE_SUBMIT_ACTION"
  | "GENERATED_DOCUMENT_NOT_FOUND"
  | "UNSUPPORTED_GENERATED_CLAIM"
  | "INVALID_SCORE_REQUEST"
  | "INVALID_RESUME_INTELLIGENCE_REQUEST"
  | "UNSUPPORTED_JOB_SOURCE";

export class ApplicationError extends Error {
  readonly code: ApplicationErrorCode;
  override readonly cause?: unknown;

  constructor(code: ApplicationErrorCode, message: string, options: { cause?: unknown } = {}) {
    super(message);
    this.name = "ApplicationError";
    this.code = code;
    this.cause = options.cause;
  }
}
